export const MEXICO_CITIES = [
    'Jesús María',
    'Pabellón de Arteaga',
    'Aguascalientes',
    'Rincón de Romos',
    'Calvillo',
    'Asientos',
    'San Francisco de los Romo',
    'Tepezalá',
    'Cosío',
    'El Llano',
    'San José de Gracia',
    'Playas de Rosarito',
    'Mexicali',
    'Ensenada',
    'Tijuana',
    'Tecate',
    'Comondú',
    'La Paz',
    'Los Cabos',
    'Mulegé',
    'Loreto',
    'Calkiní',
    'Campeche',
    'Candelaria',
    'Escárcega',
    'Carmen',
    'Champotón',
    'Palizada',
    'Hopelchén',
    'Calakmul',
    'Tenabo',
    'Hecelchakán',
    'Saltillo',
    'Progreso',
    'Juárez',
    'Piedras Negras',
    'Francisco I. Madero',
    'Matamoros',
    'Torreón',
    'Sabinas',
    'Monclova',
    'Acuña',
    'General Cepeda',
    'Castaños',
    'Cuatro Ciénegas',
    'San Buenaventura',
    'Zaragoza',
    'Múzquiz',
    'Nava',
    'San Juan de Sabinas',
    'San Pedro',
    'Jiménez',
    'Ramos Arizpe',
    'Sierra Mojada',
    'Villa Unión',
    'Nadadores',
    'Abasolo',
    'Frontera',
    'Lamadrid',
    'Ocampo',
    'Escobedo',
    'Viesca',
    'Hidalgo',
    'Parras',
    'Allende',
    'Candela',
    'Guerrero',
    'Arteaga',
    'Morelos',
    'Colima',
    'Tecomán',
    'Ixtlahuacán',
    'Manzanillo',
    'Coquimatlán',
    'Minatitlán',
    'Villa de Álvarez',
    'Cuauhtémoc',
    'Comala',
    'Armería',
    'Yajalón',
    'Reforma',
    'Tuxtla Gutiérrez',
    'Villaflores',
    'Chilón',
    'Palenque',
    'Tenejapa',
    'San Cristóbal de las Casas',
    'Ocozocoautla de Espinosa',
    'Tapachula',
    'Mezcalapa',
    'Frontera Hidalgo',
    'Cintalapa',
    'Chiapa de Corzo',
    'Tzimol',
    'Catazajá',
    'Tonalá',
    'Tuxtla Chico',
    'Teopisca',
    'Suchiate',
    'Soyaló',
    'Simojovel',
    'Pichucalco',
    'Pijijiapan',
    'Ocosingo',
    'Motozintla',
    'Comitán de Domínguez',
    'Arriaga',
    'Acala',
    'Escuintla',
    'La Concordia',
    'Jiquipilas',
    'Mapastepec',
    'Frontera Comalapa',
    'Huehuetán',
    'Benemérito de las Américas',
    'Acapetahua',
    'Chenalhó',
    'Copainalá',
    'Bochil',
    'El Porvenir',
    'Villa Comaltitlán',
    'Bella Vista',
    'Siltepec',
    'Amatenango de la Frontera',
    'Bejucal de Ocampo',
    'La Grandeza',
    'Mazapa de Madero',
    'Nicolás Ruíz',
    'Huixtla',
    'Unión Juárez',
    'Venustiano Carranza',
    'Tila',
    'Berriozábal',
    'Villa Corzo',
    'Tapilula',
    'Cacahoatán',
    'Zinacantán',
    'Chamula',
    'Oxchuc',
    'Maravilla Tenejapa',
    'La Libertad',
    'Aldama',
    'Chicomuselo',
    'Marqués de Comillas',
    'Rincón Chamula San Pedro',
    'El Parral',
    'Pantelhó',
    'Las Margaritas',
    'Altamirano',
    'Capitán Luis Ángel Vidal',
    'Chanal',
    'Angel Albino Corzo',
    'Metapa',
    'Ostuacán',
    'Sabanilla',
    'Sitalá',
    'Sunuapa',
    'Chalchihuitán',
    'Chicoasén',
    'Huixtán',
    'San Andrés Duraznal',
    'San Juan Cancuc',
    'Santiago el Pinar',
    'Larráinzar',
    'Pantepec',
    'Acacoyagua',
    'Amatenango del Valle',
    'Las Rosas',
    'Montecristo de Guerrero',
    'Osumacinta',
    'Salto de Agua',
    'Socoltenango',
    'Suchiapa',
    'Tapalapa',
    'Tuzantán',
    'La Trinitaria',
    'Tecpatán',
    'Amatán',
    'Chapultenango',
    'Chiapilla',
    'Coapilla',
    'El Bosque',
    'Emiliano Zapata',
    'Francisco León',
    'Huitiupán',
    'Ixhuatán',
    'Ixtacomitán',
    'Ixtapa',
    'Ixtapangajoya',
    'La Independencia',
    'Mazatán',
    'Ocotepec',
    'Pueblo Nuevo Solistahuacán',
    'Rayón',
    'San Fernando',
    'San Lucas',
    'Solosuchiapa',
    'Totolapa',
    'Jitotol',
    'Tumbalá',
    'Mitontic',
    'Santa Isabel',
    'Nuevo Casas Grandes',
    'Casas Grandes',
    'Chihuahua',
    'Delicias',
    'La Cruz',
    'Buenaventura',
    'Aquiles Serdán',
    'Guachochi',
    'Saucillo',
    'Camargo',
    'Gómez Farías',
    'Guadalupe y Calvo',
    'Hidalgo del Parral',
    'Balleza',
    'Bocoyna',
    'Ascensión',
    'Ahumada',
    'San Francisco del Oro',
    'Valle de Zaragoza',
    'Ojinaga',
    'Namiquipa',
    'Madera',
    'Santa Bárbara',
    'Meoqui',
    'Huejotitán',
    'Uruachi',
    'El Tule',
    'Batopilas',
    'Cusihuiriachi',
    'Rosario',
    'San Francisco de Conchos',
    'Praxedis G. Guerrero',
    'Carichí',
    'Coyame del Sotol',
    'Guadalupe',
    'López',
    'Nonoava',
    'Riva Palacio',
    'Temósachic',
    'Guazapares',
    'Ignacio Zaragoza',
    'Janos',
    'Gran Morelos',
    'Galeana',
    'San Francisco de Borja',
    'Rosales',
    'Bachíniva',
    'Satevó',
    'Dr. Belisario Domínguez',
    'Urique',
    'Julimes',
    'Coronado',
    'Chínipas',
    'Maguarichi',
    'Manuel Benavides',
    'Moris',
    'Miguel Hidalgo',
    'Iztacalco',
    'Iztapalapa',
    'Gustavo A. Madero',
    'Tlalpan',
    'Tláhuac',
    'Álvaro Obregón',
    'Xochimilco',
    'Coyoacán',
    'La Magdalena Contreras',
    'Cuajimalpa de Morelos',
    'Azcapotzalco',
    'Benito Juárez',
    'Milpa Alta',
    'Nombre de Dios',
    'Poanas',
    'Tamazula',
    'Durango',
    'Súchil',
    'Gómez Palacio',
    'Guadalupe Victoria',
    'Topia',
    'Lerdo',
    'Mapimí',
    'El Oro',
    'Guanaceví',
    'Pueblo Nuevo',
    'Pánuco de Coronado',
    'San Dimas',
    'Rodeo',
    'Santiago Papasquiaro',
    'Tepehuanes',
    'Tlahualilo',
    'San Juan del Río',
    'Vicente Guerrero',
    'Nuevo Ideal',
    'Cuencamé',
    'Nazas',
    'Canatlán',
    'Canelas',
    'Indé',
    'Coneto de Comonfort',
    'Peñón Blanco',
    'General Simón Bolívar',
    'San Pedro del Gallo',
    'San Bernardo',
    'San Juan de Guadalupe',
    'Mezquital',
    'Santa Clara',
    'San Luis del Cordero',
    'Otáez',
    'Jaral del Progreso',
    'Comonfort',
    'San Felipe',
    'Tarandacuao',
    'Moroleón',
    'Salamanca',
    'Irapuato',
    'León',
    'Celaya',
    'Pénjamo',
    'Acámbaro',
    'San Miguel de Allende',
    'Silao de la Victoria',
    'Cuerámaro',
    'San Luis de la Paz',
    'Apaseo el Grande',
    'Salvatierra',
    'Romita',
    'San José Iturbide',
    'San Francisco del Rincón',
    'Tarimoro',
    'Uriangato',
    'Apaseo el Alto',
    'Dolores Hidalgo Cuna de la Independencia Nacional',
    'Jerécuaro',
    'Villagrán',
    'Cortazar',
    'Santa Cruz de Juventino Rosas',
    'Valle de Santiago',
    'Yuriria',
    'Doctor Mora',
    'San Diego de la Unión',
    'Santa Catarina',
    'Victoria',
    'Guanajuato',
    'Manuel Doblado',
    'Coroneo',
    'Purísima del Rincón',
    'Santiago Maravatío',
    'Tierra Blanca',
    'Huanímaro',
    'Cuautepec',
    'Acapulco de Juárez',
    'Chilpancingo de los Bravo',
    'Tlapa de Comonfort',
    'Tixtla de Guerrero',
    'Xochistlahuaca',
    'Eduardo Neri',
    'Ajuchitlán del Progreso',
    'Atlixtac',
    'Coahuayutla de José María Izazaga',
    'Chilapa de Álvarez',
    'Técpan de Galeana',
    'Atoyac de Álvarez',
    'Pilcaya',
    'Iguala de la Independencia',
    'Taxco de Alarcón',
    'Huitzuco de los Figueroa',
    'Zihuatanejo de Azueta',
    'Pungarabato',
    'La Unión de Isidoro Montes de Oca',
    'Juchitán',
    'Buenavista de Cuéllar',
    'Tecoanapa',
    'Tetipac',
    'Juan R. Escudero',
    'Arcelia',
    'Copala',
    'Huamuxtitlán',
    'Mochitlán',
    'Ometepec',
    'San Luis Acatlán',
    'Tepecoacuilco de Trujano',
    'Coyuca de Benítez',
    'San Marcos',
    'Cuajinicuilapa',
    'General Canuto A. Neri',
    'Copanatoyac',
    'Atlamajalcingo del Monte',
    'Malinaltepec',
    'Ixcateopan de Cuauhtémoc',
    'Pedro Ascencio Alquisiras',
    'Tlalixtaquilla de Maldonado',
    'Ahuacuotzingo',
    'Alcozauca de Guerrero',
    'Alpoyeca',
    'Cuetzala del Progreso',
    'Iliatenco',
    'Xochihuehuetlán',
    'Apaxtla',
    'Cocula',
    'Zirándaro',
    'Atenango del Río',
    'Mártir de Cuilapan',
    'Tlapehuala',
    'Tlalchapa',
    'Cutzamala de Pinzón',
    'Coyuca de Catalán',
    'Ayutla de los Libres',
    'Florencio Villarreal',
    'Acatepec',
    'General Heliodoro Castillo',
    'Quechultenango',
    'José Joaquín de Herrera',
    'Xalpatláhuac',
    'Zapotitlán Tablas',
    'Teloloapan',
    'Cualác',
    'Petatlán',
    'Metlatónoc',
    'Cochoapa el Grande',
    'San Miguel Totolapan',
    'Azoyú',
    'Marquelia',
    'Olinalá',
    'Tlacoapa',
    'Tlacoachistlahuaca',
    'Zitlala',
    'Igualapa',
    'Leonardo Bravo',
    'Jaltocán',
    'Tepehuacán de Guerrero',
    'Tlanchinol',
    'Pacula',
    'Tula de Allende',
    'Huejutla de Reyes',
    'Tepeji del Río de Ocampo',
    'Acaxochitlán',
    'Alfajayucan',
    'Pachuca de Soto',
    'Tasquillo',
    'Tezontepec de Aldama',
    'Tizayuca',
    'Mineral del Monte',
    'Singuilucan',
    'Zapotlán de Juárez',
    'Actopan',
    'Mineral de la Reforma',
    'Tulancingo de Bravo',
    'San Salvador',
    'Atitalaquia',
    'Huichapan',
    'Tecozautla',
    'Ixmiquilpan',
    'Ajacuba',
    'Metztitlán',
    'Atotonilco el Grande',
    'Almoloya',
    'Lolotla',
    'Progreso de Obregón',
    'Atotonilco de Tula',
    'Huasca de Ocampo',
    'Huazalingo',
    'Cuautepec de Hinojosa',
    'Jacala de Ledezma',
    'San Agustín Tlaxiaca',
    'Calnali',
    'Huautla',
    'Zimapán',
    'Nopala de Villagrán',
    'Xochiatipan',
    'Mixquiahuala de Juárez',
    'Santiago Tulantepec de Lugo Guerrero',
    'San Bartolo Tutotepec',
    'Tlahuelilpan',
    'Tlaxcoapan',
    'Cardonal',
    'Santiago de Anaya',
    'Juárez Hidalgo',
    'Atlapexco',
    'Agua Blanca de Iturbide',
    'Tepeapulco',
    'San Felipe Orizatlán',
    'Tolcayuca',
    'Villa de Tezontepec',
    'Tetepango',
    'Apan',
    'Tenango de Doria',
    'Huehuetla',
    'Mineral del Chico',
    'El Arenal',
    'Metepec',
    'Zempoala',
    'Eloxochitlán',
    'Chapantongo',
    'Molango de Escamilla',
    'Tianguistengo',
    'Acatlán',
    'Chapulhuacán',
    'Chilcuautla',
    'Tlahuiltepa',
    'Pisaflores',
    'Tlanalapa',
    'La Misión',
    'San Agustín Metzquititlán',
    'Zacualtipán de Ángeles',
    'Xochicoatlán',
    'Yahualica',
    'Nicolás Flores',
    'Tepetitlán',
    'Omitlán de Juárez',
    'Epazoyucan',
    'Guadalajara',
    'Ojuelos de Jalisco',
    'Puerto Vallarta',
    'Santa María de los Ángeles',
    'Ixtlahuacán de los Membrillos',
    'Ayutla',
    'Chiquilistlán',
    'Cuautla',
    'Pihuamo',
    'Poncitlán',
    'Tenamaxtlán',
    'Atengo',
    'Tala',
    'Tequila',
    'Ocotlán',
    'Juchitlán',
    'Etzatlán',
    'Cañadas de Obregón',
    'Tonaya',
    'Encarnación de Díaz',
    'Atotonilco el Alto',
    'Zapotlán del Rey',
    'Zacoalco de Torres',
    'Zapotlanejo',
    'Juanacatlán',
    'Tepatitlán de Morelos',
    'Zapopan',
    'Villa Hidalgo',
    'Lagos de Moreno',
    'Ayotlán',
    'Acatlán de Juárez',
    'Autlán de Navarro',
    'Ameca',
    'Tototlán',
    'Tlajomulco de Zúñiga',
    'Chapala',
    'Talpa de Allende',
    'Tecolotlán',
    'El Salto',
    'San Juan de los Lagos',
    'Tuxpan',
    'Tamazula de Gordiano',
    'Ahualulco de Mercado',
    'Amatitán',
    'San Martín Hidalgo',
    'Tomatlán',
    'San Pedro Tlaquepaque',
    'Acatic',
    'Zapotiltic',
    'Colotlán',
    'Cuquío',
    'El Grullo',
    'La Manzanilla de la Paz',
    'Mascota',
    'Mexticacán',
    'Jocotepec',
    'Ixtlahuacán del Río',
    'Huejúcar',
    'La Huerta',
    'Jalostotitlán',
    'Jamay',
    'Tapalpa',
    'Tecalitlán',
    'Teocuitatlán de Corona',
    'San Miguel el Alto',
    'San Julián',
    'Arandas',
    'Cihuatlán',
    'Zapotlán el Grande',
    'Yahualica de González Gallo',
    'San Gabriel',
    'Villa Guerrero',
    'Unión de Tula',
    'Tizapán el Alto',
    'San Sebastián del Oeste',
    'Tolimán',
    'Sayula',
    'San Juanito de Escobedo',
    'Quitupan',
    'Huejuquilla el Alto',
    'Mezquitic',
    'Techaluta de Montenegro',
    'Atemajac de Brizuela',
    'Tonila',
    'Mazamitla',
    'Tuxcueca',
    'Guachinango',
    'Hostotipaquillo',
    'Teuchitlán',
    'Valle de Guadalupe',
    'Totatiche',
    'Cuautitlán de García Barragán',
    'Concepción de Buenos Aires',
    'Santa María del Oro',
    'Jilotlán de los Dolores',
    'San Diego de Alejandría',
    'Valle de Juárez',
    'Tuxcacuesco',
    'El Limón',
    'Villa Corona',
    'Teocaltiche',
    'Ejutla',
    'San Martín de Bolaños',
    'Chimaltitán',
    'Bolaños',
    'San Cristóbal de la Barranca',
    'La Barca',
    'Atenguillo',
    'Mixtlán',
    'Unión de San Antonio',
    'Magdalena',
    'Degollado',
    'Zapotitlán de Vadillo',
    'Atoyac',
    'San Ignacio Cerro Gordo',
    'Villa Purificación',
    'Casimiro Castillo',
    'Cabo Corrientes',
    'Amacueca',
    'Tlalnepantla de Baz',
    'Tlalmanalco',
    'Chapultepec',
    'Cuautitlán Izcalli',
    'Coyotepec',
    'Toluca',
    'Tepotzotlán',
    'Jilotzingo',
    'Tepetlaoxtoc',
    'Ixtapaluca',
    'San Martín de las Pirámides',
    'Zumpango',
    'Nicolás Romero',
    'Temascaltepec',
    'Temascalapa',
    'Tianguistenco',
    'Ixtapan del Oro',
    'Ixtlahuaca',
    'Mexicaltzingo',
    'Amecameca',
    'Atizapán de Zaragoza',
    'Huixquilucan',
    'Valle de Chalco Solidaridad',
    'Lerma',
    'Tultitlán',
    'Atenco',
    'Almoloya del Río',
    'Papalotla',
    'Tepetlixpa',
    'Zumpahuacán',
    'Atlacomulco',
    'Ecatepec de Morelos',
    'Chimalhuacán',
    'Naucalpan de Juárez',
    'Acolman',
    'Cuautitlán',
    'Tequixquiac',
    'Tecámac',
    'Chalco',
    'Chiconcuac',
    'Nezahualcóyotl',
    'Chicoloapan',
    'Coacalco de Berriozábal',
    'Tezoyuca',
    'Valle de Bravo',
    'Villa del Carbón',
    'San Felipe del Progreso',
    'Zinacantepec',
    'Tenango del Valle',
    'Texcoco',
    'Ayapango',
    'Atlautla',
    'Ecatzingo',
    'Tejupilco',
    'Tonatico',
    'San Mateo Atenco',
    'Cocotitlán',
    'Temamatla',
    'Tenango del Aire',
    'Juchitepec',
    'Tenancingo',
    'Almoloya de Juárez',
    'Tultepec',
    'Calimaya',
    'Xalatlaco',
    'Ocoyoacac',
    'Chiautla',
    'Joquicingo',
    'Temascalcingo',
    'Otzoloapan',
    'Chapa de Mota',
    'Teotihuacán',
    'Tlatlaya',
    'Jocotitlán',
    'Soyaniquilpan de Juárez',
    'Villa de Allende',
    'Acambay de Ruíz Castañeda',
    'Zacazonapan',
    'Ocuilan',
    'Luvianos',
    'Hueypoxtla',
    'Ozumba',
    'San Simón de Guerrero',
    'Villa Victoria',
    'Jiquipilco',
    'Apaxco',
    'Sultepec',
    'Huehuetoca',
    'Melchor Ocampo',
    'Tonanitla',
    'San Antonio la Isla',
    'Xonacatlán',
    'Donato Guerra',
    'Amanalco',
    'Amatepec',
    'Teoloyucan',
    'Otzolotepec',
    'Temoaya',
    'Santo Tomás',
    'Polotitlán',
    'San José del Rincón',
    'Isidro Fabela',
    'Jilotepec',
    'Aculco',
    'Malinalco',
    'Coatepec Harinas',
    'Nextlalpan',
    'Jaltenco',
    'Ixtapan de la Sal',
    'Almoloya de Alquisiras',
    'Texcalyacac',
    'Atizapán',
    'Zacualpan',
    'Nopaltepec',
    'Timilpan',
    'Axapusco',
    'Otumba',
    'Texcaltitlán',
    'Capulhuac',
    'Morelia',
    'Parácuaro',
    'Tangancícuaro',
    'Huetamo',
    'Irimbo',
    'Tzitzio',
    'La Piedad',
    'José Sixto Verduzco',
    'Lázaro Cárdenas',
    'Tacámbaro',
    'Buenavista',
    'Zacapu',
    'Jiquilpan',
    'Zamora',
    'Erongarícuaro',
    'Jacona',
    'Cuitzeo',
    'Nuevo Parangaricutiro',
    'Uruapan',
    'Zitácuaro',
    'Los Reyes',
    'Angangueo',
    'Ario',
    'Marcos Castellanos',
    'Pátzcuaro',
    'La Huacana',
    'Angamacutiro',
    'Salvador Escalante',
    'Paracho',
    'Sahuayo',
    'Quiroga',
    'Puruándiro',
    'Gabriel Zamora',
    'Maravatío',
    'Apatzingán',
    'Cotija',
    'Coahuayana',
    'Tanhuato',
    'Vista Hermosa',
    'Yurécuaro',
    'Tepalcatepec',
    'Purépero',
    'Churumuco',
    'Pajacuarán',
    'Tarímbaro',
    'Coeneo',
    'Nuevo Urecho',
    'Chinicuila',
    'Epitacio Huerta',
    'Briseñas',
    'Cherán',
    'Acuitzio',
    'Charo',
    'Chavinda',
    'Múgica',
    'Peribán',
    'Queréndaro',
    'Villamar',
    'Ziracuaretiro',
    'Ixtlán',
    'Nahuatzen',
    'Zinapécuaro',
    'Tingambato',
    'Contepec',
    'Numarán',
    'Aguililla',
    'Carácuaro',
    'Aquila',
    'Tangamandapio',
    'Turicato',
    'Tzintzuntzan',
    'Panindícuaro',
    'Tiquicheo de Nicolás Romero',
    'Indaparapeo',
    'Tlazazalca',
    'Cojumatlán de Régules',
    'Churintzio',
    'Santa Ana Maya',
    'Charapan',
    'Chilchota',
    'Tancítaro',
    'Tocumbo',
    'Huiramba',
    'Coalcomán de Vázquez Pallares',
    'Penjamillo',
    'Aporo',
    'Chucándiro',
    'Copándaro',
    'Huaniqueo',
    'Lagunillas',
    'Tumbiscatío',
    'Tingüindín',
    'Madero',
    'Huandacareo',
    'Ecuandureo',
    'Senguio',
    'Tuzantla',
    'Jungapeo',
    'Nocupétaro',
    'Taretan',
    'Zináparo',
    'Tlalpujahua',
    'Susupuato',
    'Jiutepec',
    'Xochitepec',
    'Cuernavaca',
    'Yautepec',
    'Temixco',
    'Puente de Ixtla',
    'Jojutla',
    'Jonacatepec',
    'Huitzilac',
    'Axochiapan',
    'Miacatlán',
    'Tlaquiltenango',
    'Coatlán del Río',
    'Tlaltizapán de Zapata',
    'Tetela del Volcán',
    'Yecapixtla',
    'Ayala',
    'Tetecala',
    'Ocuituco',
    'Tepalcingo',
    'Tlalnepantla',
    'Zacatepec',
    'Tepoztlán',
    'Tlayacapan',
    'Jantetelco',
    'Mazatepec',
    'Temoac',
    'Amacuzac',
    'Coatetelco',
    'Xoxocotla',
    'Atlatlahucan',
    'Totolapan',
    'Amatlán de Cañas',
    'Tepic',
    'Bahía de Banderas',
    'Ixtlán del Río',
    'Compostela',
    'Tecuala',
    'Del Nayar',
    'Santiago Ixcuintla',
    'Ruíz',
    'San Blas',
    'Acaponeta',
    'Ahuacatlán',
    'Xalisco',
    'Rosamorada',
    'La Yesca',
    'Huajicori',
    'Jala',
    'San Pedro Lagunillas',
    'San Nicolás de los Garza',
    'Bustamante',
    'Cadereyta Jiménez',
    'General Escobedo',
    'Higueras',
    'Hualahuises',
    'General Zuazua',
    'Monterrey',
    'Salinas Victoria',
    'García',
    'Apodaca',
    'Santiago',
    'San Pedro Garza García',
    'Montemorelos',
    'Aramberri',
    'Villaldama',
    'Sabinas Hidalgo',
    'Los Ramones',
    'Linares',
    'Marín',
    'Cerralvo',
    'China',
    'Doctor Arroyo',
    'Anáhuac',
    'General Terán',
    'Los Herreras',
    'Doctor Coss',
    'Los Aldamas',
    'Mina',
    'El Carmen',
    'Iturbide',
    'Agualeguas',
    'General Bravo',
    'Lampazos de Naranjo',
    'General Treviño',
    'Parás',
    'Doctor González',
    'Ciénega de Flores',
    'Pesquería',
    'San José Estancia Grande',
    'Santa María Xadani',
    'Santiago Tapextla',
    'Santo Domingo Armenta',
    'Tlacolula de Matamoros',
    'Santiago Pinotepa Nacional',
    'San Pedro Mixtepec -Dto. 22 -',
    'Santa María Colotepec',
    'San Francisco Ixhuatán',
    'Chahuites',
    'San Pedro Tapanatepec',
    'Reforma de Pineda',
    'Acatlán de Pérez Figueroa',
    'San Agustín Chayuco',
    'Santiago Jamiltepec',
    'San Pablo Villa de Mitla',
    'Salina Cruz',
    'Cosolapa',
    'Santiago Yolomécatl',
    'Heroica Ciudad de Juchitán de Zaragoza',
    'San Juan Cotzocón',
    'Magdalena Tequisistlán',
    'Santo Domingo Tehuantepec',
    'San Lorenzo',
    'Santiago Ixtayutla',
    'Santiago Tetepec',
    'Santa María Huazolotitlán',
    'Santa Catarina Juquila',
    'Santa Catarina Mechoacán',
    'San Dionisio Ocotepec',
    'San Miguel Tlacotepec',
    'San Pedro Ixtlahuaca',
    'Santa María Atzompa',
    'Tataltepec de Valdés',
    'Villa Sola de Vega',
    'Ciénega de Zimatlán',
    'San Miguel Soyaltepec',
    'San Antonino Castillo Velasco',
    'San Pedro Quiatoni',
    'San Agustín Loxicha',
    'Oaxaca de Juárez',
    'San Agustín Yatareni',
    'Santa María Huatulco',
    'Asunción Ocotlán',
    'La Compañía',
    'La Pe',
    'San Agustín Amatengo',
    'San Jerónimo Coatlán',
    'San Martín de los Cansecos',
    'San Martín Tilcajete',
    'San Miguel Coatlán',
    'San Miguel Huautla',
    'San Pablo Coatlán',
    'San Pedro Mártir Quiechapa',
    'San Sebastián Coatlán',
    'San Vicente Coatlán',
    'Santa Ana',
    'Santa Ana Zegache',
    'Santa Cruz Xitla',
    'Yaxe',
    'San Juan Chilateca',
    'Santa Catarina Cuixtla',
    'Sitio de Xitlapehua',
    'Fresnillo de Trujano',
    'San José del Peñasco',
    'San Lucas Zoquiápam',
    'Santiago Suchilquitongo',
    'Santa María del Tule',
    'San Juan Bautista Tuxtepec',
    'Asunción Tlacolulita',
    'Santo Domingo Zanatepec',
    'Villa de Etla',
    'Villa de Tamazulápam del Progreso',
    'Ocotlán de Morelos',
    'Ciudad Ixtepec',
    'Heroica Ciudad de Huajuapan de León',
    'San Bartolomé Zoogocho',
    'San Andrés Huayápam',
    'Nejapa de Madero',
    'Santa María Tepantlali',
    'Villa de Tututepec de Melchor Ocampo',
    'San Pablo Etla',
    'Santa Cruz Amilpas',
    'Santo Domingo Tonalá',
    'Silacayoápam',
    'Unión Hidalgo',
    'Teotitlán de Flores Magón',
    'San Pedro Pochutla',
    'San Pedro y San Pablo Ayutla',
    'Santiago Juxtlahuaca',
    'Villa Talea de Castro',
    'San Felipe Jalapa de Díaz',
    'Loma Bonita',
    'Mariscala de Juárez',
    'Matías Romero Avendaño',
    'Huautla de Jiménez',
    'Miahuatlán de Porfirio Díaz',
    'Chalcatongo de Hidalgo',
    'Asunción Nochixtlán',
    'San Juan Cacahuatepec',
    'Ixtlán de Juárez',
    'Zimatlán de Álvarez',
    'Villa de Zaachila',
    'Putla Villa de Guerrero',
    'San Ildefonso Villa Alta',
    'Heroica Villa Tezoatlán de Segura y Luna, Cuna de la Independencia de Oaxaca',
    'El Espinal',
    'Guadalupe de Ramírez',
    'Santa María Pápalo',
    'Guadalupe Etla',
    'Santa Ana Yareni',
    'Teococuilco de Marcos Pérez',
    'Santiago Yaitepec',
    'Santiago Lachiguiri',
    'San Bartolo Soyaltepec',
    'San Mateo Sindihui',
    'Valerio Trujano',
    'San Juan Diuxi',
    'San Mateo Piñas',
    'San Miguel Aloápam',
    'San Miguel Amatitlán',
    'San Miguel Chicahua',
    'San Miguel Panixtlahuaca',
    'San Miguel Peras',
    'San Miguel Piedras',
    'San Miguel Quetzaltepec',
    'San Miguel Tequixtepec',
    'San Miguel Tulancingo',
    'San Miguel Yotao',
    'San Juan Evangelista Analco',
    'San Juan Ihualtepec',
    'San Juan Juquila Mixes',
    'San Juan Mazatlán',
    'San Juan Quiahije',
    'San Juan Quiotepec',
    'San Juan Sayultepec',
    'San Juan Tabaá',
    'San Juan Chicomezúchil',
    'San Juan Cieneguilla',
    'San Juan Comaltepec',
    'San Lorenzo Victoria',
    'San Lucas Camotlán',
    'San Lucas Quiaviní',
    'San Lorenzo Albarradas',
    'San Lorenzo Cacaotepec',
    'San Lorenzo Cuaunecuiltitla',
    'San Juan Tepeuxila',
    'San Juan Teposcolula',
    'San Juan Yatzona',
    'San Baltazar Yatzachi el Bajo',
    'San Bernardo Mixtepec',
    'San Cristóbal Suchixtlahuaca',
    'San Andrés Yaá',
    'San Andrés Zautla',
    'San Andrés Ixtlahuaca',
    'San Andrés Nuxiño',
    'San Andrés Sinaxtla',
    'San Andrés Solaga',
    'San Andrés Teotilálpam',
    'San Antonio Acutla',
    'San Antonio Tepetlapa',
    'San Bartolomé Ayautla',
    'San Bartolomé Loxicha',
    'San Francisco Teopan',
    'San Jerónimo Silacayoapilla',
    'San Jerónimo Sosola',
    'San Francisco Cajonos',
    'San Francisco Chindúa',
    'San Francisco Jaltepetongo',
    'San Francisco Huehuetlán',
    'San Juan Atepec',
    'San Juan Bautista Tlachichilco',
    'San José Ayuquila',
    'San José Tenango',
    'San Juan Bautista Atatlahuca',
    'San Juan Bautista Guelache',
    'San Juan Bautista Jayacatlán',
    'Santa María Ecatepec',
    'Santa María Guelacé',
    'Villa de Chilapa de Díaz',
    'Santa María Peñoles',
    'Santa María Texcatitlán',
    'Santa María Tlahuitoltepec',
    'Santa María Tonameca',
    'Santa María Sola',
    'Santa María Temaxcalapa',
    'Santa María Teopoxco',
    'Santiago Matatlán',
    'Santiago Nacaltepec',
    'Santiago Nejapilla',
    'Santiago Nuyoó',
    'Villa Tejúpam de la Unión',
    'Santiago Tenango',
    'Santiago Texcalcingo',
    'Santiago Textitlán',
    'Santiago Huauclilla',
    'Santiago Ihuitlán Plumas',
    'Santiago Atitlán',
    'Santiago Comaltepec',
    'Santiago Chazumba',
    'Santiago Choápam',
    'Santa María Yalina',
    'Santa María Yolotepec',
    'Santa María Zaniza',
    'Santiago Apoala',
    'San Pedro Topiltepec',
    'San Pedro Yólox',
    'San Pedro Nopala',
    'San Pedro Ocotepec',
    'San Pedro Mixtepec -Dto. 26 -',
    'San Pedro Jaltepetongo',
    'San Pedro Jocotipac',
    'San Pedro Juchatengo',
    'San Pedro Coxcaltepec Cántaros',
    'San Pedro Comitancillo',
    'Santa Ana Tavela',
    'Santa Catarina Lachatao',
    'Santa Catarina Quiané',
    'Santa Cruz Acatepec',
    'Santa Cruz Itundujia',
    'Santa Cruz Mixtepec',
    'Santa Cruz Tacache de Mina',
    'Santa María Alotepec',
    'Santa María Apazco',
    'Santa María la Asunción',
    'Eloxochitlán de Flores Magón',
    'Mesones Hidalgo',
    'Tamazulápam del Espíritu Santo',
    'Magdalena Jaltepec',
    'Santa Magdalena Jicotlán',
    'Ixpantepec Nieves',
    'Mazatlán Villa de Flores',
    'Mixistlán de la Reforma',
    'Nazareno Etla',
    'Reyes Etla',
    'Pinotepa de Don Luis',
    'San Agustín Atenango',
    'Abejones',
    'Asunción Cacalotepec',
    'Chiquihuitlán de Benito Juárez',
    'Cuyamecalco Villa de Zaragoza',
    'Concepción Buenavista',
    'Totontepec Villa de Morelos',
    'La Trinidad Vista Hermosa',
    'Magdalena Yodocono de Porfirio Díaz',
    'Teotitlán del Valle',
    'Teotongo',
    'Tepelmeme Villa de Morelos',
    'Villa Díaz Ordaz',
    'Santiago Xanica',
    'Santiago Zacatepec',
    'Santiago Zoochila',
    'Nuevo Zoquiápam',
    'Santo Domingo Albarradas',
    'Santo Domingo Roayaga',
    'Santo Domingo Teojomulco',
    'Santo Domingo Tepuxtepec',
    'Soledad Etla',
    'San Vicente Lachixío',
    'Santo Tomás Mazaltepec',
    'Santo Domingo Tonaltepec',
    'Santo Domingo Xagacía',
    'Santos Reyes Pápalo',
    'San Simón Almolongas',
    'Cuilápam de Guerrero',
    'El Barrio de la Soledad',
    'Candelaria Loxicha',
    'Santa Cruz Xoxocotlán',
    'San Agustín de las Juntas',
    'San Antonio de la Cal',
    'San Bartolo Coyotepec',
    'San Bartolo Yautepec',
    'San Carlos Yautepec',
    'San Francisco Sola',
    'San Juan Achiutla',
    'San Juan Lajarcia',
    'San Juan Teitipac',
    'San Mateo Etlatongo',
    'San Miguel Tenango',
    'San Miguel Tilquiápam',
    'San Nicolás',
    'San Pedro Taviche',
    'Santa Catarina Zapoquila',
    'Santa Inés de Zaragoza',
    'Santa María Zoquitlán',
    'Santa María Mixtequilla',
    'Santa María Quiegolani',
    'Santa María Totolapilla',
    'Santiago Apóstol',
    'Santiago Laxopa',
    'Tlacotepec Plumas',
    'San Juan Tamazola',
    'San Miguel Tecomatlán',
    'Santiago Tillo',
    'Santo Domingo Yanhuitlán',
    'Santa María Jaltianguis',
    'San Pedro Tidaá',
    'San Andrés Zabache',
    'San Felipe Tejalápam',
    'San Francisco Lachigoló',
    'San Francisco Nuxaño',
    'San Jerónimo Tlacochahuaya',
    'San Juan Bautista Coixtlahuaca',
    'Coatecas Altas',
    'San Juan Guelavía',
    'San Juan Lachigalla',
    'San Juan Lalana',
    'San Mateo Tlapiltepec',
    'San Mateo Yucutindoo',
    'San Melchor Betaza',
    'San Miguel Mixtepec',
    'San Sebastián Abasolo',
    'Santa Ana Tlapacoyan',
    'Santa Catarina Ixtepeji',
    'Santa Catarina Minas',
    'Santa Cruz Papalutla',
    'Santa Cruz Zenzontepec',
    'Santiago Jocotepec',
    'Santiago Minas',
    'Santiago Tlazoyaltepec',
    'Santo Domingo Nuxaá',
    'Santo Tomás Jalieza',
    'Santo Tomás Tamazulapan',
    'San Pablo Huitzo',
    'San Sebastián Teitipac',
    'Santa Lucía del Camino',
    'Tlalixtac de Cabrera',
    'Santo Domingo Yodohino',
    'Santo Domingo Tomaltepec',
    'Santa Lucía Ocotlán',
    'San Miguel Ahuehuetitlán',
    'San Jerónimo Tecóatl',
    'San José del Progreso',
    'San Andrés Dinicuiti',
    'Coicoyán de las Flores',
    'San Francisco Ozolotepec',
    'San Miguel del Río',
    'San Martín Itunyoso',
    'San Mateo Cajonos',
    'San Pablo Cuatro Venados',
    'San Pedro Cajonos',
    'San Juan Yaeé',
    'San Lorenzo Texmelúcan',
    'San Juan Juquila Vijanos',
    'San Juan Mixtepec -Dto. 08 -',
    'Santa María Ixcatlán',
    'Santiago Ixcuintepec',
    'Santa Inés del Monte',
    'San Pedro Teozacoalco',
    'Tanetze de Zaragoza',
    'Santos Reyes Yucuná',
    'San Vicente Nuñú',
    'Santo Domingo de Morelos',
    'Magdalena Ocotlán',
    'San Juan del Estado',
    'Trinidad Zaachila',
    'San Baltazar Loxicha',
    'Santa Catarina Loxicha',
    'Magdalena Teitipac',
    'San Francisco del Mar',
    'Santa Gertrudis',
    'Santiago Astata',
    'Yutanduchi de Guerrero',
    'Santa Ana del Valle',
    'San Miguel Amatlán',
    'San Francisco Telixtlahuaca',
    'San Pedro Amuzgos',
    'La Reforma',
    'San Martín Lachilá',
    'San Juan de los Cués',
    'Santa María Coyotepec',
    'Santo Domingo Chihuitán',
    'San Mateo Nejápam',
    'San Cristóbal Lachirioag',
    'San Jorge Nuchita',
    'Zapotitlán Palmas',
    'Santa María Tecomavaca',
    'Santa María Yucuhiti',
    'Santa María Zacatepec',
    'San Jacinto Amilpas',
    'Heroica Ciudad de Ejutla de Crespo',
    'San Juan Bautista Cuicatlán',
    'Santiago Huajolotitlán',
    'San Pablo Huixtepec',
    'Asunción Ixtaltepec',
    'Santo Domingo Ingenio',
    'Santa María Ipalapa',
    'Santiago Llano Grande',
    'San Sebastián Ixcapa',
    'Santiago del Río',
    'San Juan Colorado',
    'San Miguel Tlacamama',
    'San Juan Bautista Lo de Soto',
    'San Sebastián Tecomaxtlahuaca',
    'San Cristóbal Amatlán',
    'San Ildefonso Amatlán',
    'San Juan Coatzóspam',
    'San Juan Mixtepec -Dto. 26 -',
    'San Juan Yucuita',
    'San Martín Peras',
    'Santa Catalina Quierí',
    'Santa Catarina Quioquitani',
    'Santa Lucía Miahuatlán',
    'Santiago Tamazola',
    'San Nicolás Hidalgo',
    'Mártires de Tacubaya',
    'Calihualá',
    'Zapotitlán Lagunas',
    'San Andrés Paxtlán',
    'Santa María Chachoápam',
    'San Simón Zahuatlán',
    'Santiago Cacaloxtepec',
    'San Andrés Tepetlapa',
    'San Marcial Ozolotepec',
    'Santa María Jalapa del Marqués',
    'San Marcos Arteaga',
    'San Antonio Huitepec',
    'San Blas Atempa',
    'San Agustín Etla',
    'San Bartolomé Quialana',
    'San Francisco Tlapancingo',
    'San Pedro Jicayán',
    'Santiago Tepetlapa',
    'San Pedro Atoyac',
    'Santo Tomás Ocotepec',
    'Heroica Ciudad de Tlaxiaco',
    'Santa María Nduayaco',
    'San Sebastián Nicananduta',
    'Santa Catarina Ticuá',
    'Santiago Yosondúa',
    'Santo Domingo Ixcatlán',
    'Santa Catarina Yosonotú',
    'Santa Catarina Tayata',
    'Santa Lucía Monteverde',
    'Santa Cruz Tacahua',
    'Santa Cruz Tayata',
    'Santa Cruz Nundaco',
    'San Pedro y San Pablo Teposcolula',
    'San Pedro Yucunama',
    'San Pedro Molinos',
    'San Pedro Mártir Yucuxaco',
    'Santa María Tataltepec',
    'Santa María del Rosario',
    'Santiago Nundiche',
    'Santiago Amoltepec',
    'Santa María Yosoyúa',
    'San Miguel el Grande',
    'San Mateo Peñasco',
    'San Miguel Achiutla',
    'San Pablo Tijaltepec',
    'San Martín Huamelúlpam',
    'San Juan Ñumí',
    'San Juan Teita',
    'San Esteban Atatlahuca',
    'San Cristóbal Amoltepec',
    'San Bartolomé Yucuañe',
    'San Antonio Sinicahua',
    'San Antonino Monte Verde',
    'San Andrés Lagunas',
    'San Andrés Cabecera Nueva',
    'San Agustín Tlacotepec',
    'Magdalena Peñasco',
    'San Juan Ozolotepec',
    'Ayoquezco de Aldama',
    'San Dionisio Ocotlán',
    'San Sebastián Tutla',
    'San Pedro Huilotepec',
    'San Miguel Suchixtepec',
    'San Pedro el Alto',
    'San Luis Amatlán',
    'Santa María Ozolotepec',
    'Santo Domingo Ozolotepec',
    'San Francisco Logueche',
    'San Mateo Río Hondo',
    'San Sebastián Río Hondo',
    'Santiago Camotlán',
    'Santiago Tilantongo',
    'Santo Domingo Tlatayápam',
    'Santa María Lachixío',
    'Constancia del Rosario',
    'Huautepec',
    'Santiago Ayuquililla',
    'San Pedro Sochiápam',
    'Santos Reyes Tepejillo',
    'San Antonio Nanahuatípam',
    'San Pedro Apóstol',
    'San Martín Toxpalan',
    'Rojas de Cuauhtémoc',
    'Monjas',
    'Santa María Nativitas',
    'San Baltazar Chichicápam',
    'San Miguel Ejutla',
    'Magdalena Zahuatlán',
    'San Pedro Ocopetatillo',
    'San Jerónimo Taviche',
    'Taniche',
    'Yogana',
    'San Martín Zacatepec',
    'San Pablo Macuiltianguis',
    'San Francisco Chapulapa',
    'Santiago Miltepec',
    'San Juan Bautista Suchitepec',
    'Ánimas Trujano',
    'San Felipe Usila',
    'San Francisco Cahuacuá',
    'San Jacinto Tlacotepec',
    'San Gabriel Mixtepec',
    'San Antonino el Alto',
    'San Pablo Yaganiza',
    'San Miguel Santa Flor',
    'Capulálpam de Méndez',
    'San Mateo Yoloxochitlán',
    'San Juan Petlapa',
    'San Juan Lachao',
    'Santiago Lalopa',
    'Santa María Yavesía',
    'Santa María Petapa',
    'Santa María Temaxcaltepec',
    'Santa María Tlalixtac',
    'Santa Cruz de Bravo',
    'Santa Ana Cuauhtémoc',
    'San Pedro Yaneri',
    'Magdalena Mixtepec',
    'Natividad',
    'Ayotzintepec',
    'Santiago Yucuyachi',
    'Santiago Xiacuí',
    'Asunción Cuyotepeji',
    'Cosoltepec',
    'San Pedro Huamelula',
    'San Dionisio del Mar',
    'San Pedro Totolápam',
    'Santiago Niltepec',
    'Santa María Jacatepec',
    'San Miguel Chimalapa',
    'Santa Ana Ateixtlahuaca',
    'San Ildefonso Sola',
    'San Pedro Ixcatlán',
    'Santa Inés Yatzeche',
    'San Andrés Huaxpaltepec',
    'Santa María Camotlán',
    'Guelatao de Juárez',
    'San Juan Bautista Tlacoatzintepec',
    'San José Chiltepec',
    'San Raymundo Jalpan',
    'Magdalena Tlacotepec',
    'San Lucas Ojitlán',
    'Magdalena Apasco',
    'Santos Reyes Nopala',
    'San Juan Bautista Valle Nacional',
    'San José Independencia',
    'Santa María Cortijo',
    'Amixtlán',
    'Quimixtlán',
    'San Juan Atenco',
    'Zautla',
    'Los Reyes de Juárez',
    'Santo Tomás Hueyotlipan',
    'Atoyatempan',
    'Tecali de Herrera',
    'San Salvador el Seco',
    'San Andrés Cholula',
    'Puebla',
    'Amozoc',
    'Jalpan',
    'Jopala',
    'Tecamachalco',
    'Tepanco de López',
    'Tlacotepec de Benito Juárez',
    'Coxcatlán',
    'Cuapiaxtla de Madero',
    'La Magdalena Tlatlauquitepec',
    'Xochitlán Todos Santos',
    'Caltepec',
    'Xochiltepec',
    'Ixcamilpa de Guerrero',
    'San José Miahuatlán',
    'Zoquitlán',
    'Zinacatepec',
    'San Pedro Cholula',
    'Tzicatlacoyan',
    'Tepeyahualco',
    'Izúcar de Matamoros',
    'Atlixco',
    'Naupan',
    'San Jerónimo Xayacatlán',
    'Tehuacán',
    'Cuautempan',
    'San Felipe Tepatlán',
    'Zapotitlán',
    'Xicotepec',
    'Huauchinango',
    'Tepeaca',
    'Teziutlán',
    'Atzitzintla',
    'San Martín Texmelucan',
    'Huatlatlauca',
    'Santa Isabel Cholula',
    'San Felipe Teotlalcingo',
    'Huejotzingo',
    'San Sebastián Tlacotepec',
    'Tepexi de Rodríguez',
    'Chignahuapan',
    'Hueytamalco',
    'Ocoyucan',
    'Honey',
    'San Gregorio Atzompa',
    'Libres',
    'Quecholac',
    'Xayacatlán de Bravo',
    'Acajete',
    'San Gabriel Chilac',
    'Teopantlán',
    'Chinantla',
    'Chilchotla',
    'Francisco Z. Mena',
    'General Felipe Ángeles',
    'Chietla',
    'Juan C. Bonilla',
    'Jolalpan',
    'Ixtacamaxtitlán',
    'Atzitzihuacán',
    'Chalchicomula de Sesma',
    'Tepeyahualco de Cuauhtémoc',
    'Tilapa',
    'Tlachichuca',
    'San Nicolás Buenos Aires',
    'San Salvador el Verde',
    'Huehuetlán el Grande',
    'Mixtla',
    'Zacapoaxtla',
    'Palmar de Bravo',
    'Albino Zertuche',
    'Tehuitzingo',
    'Tlatlauquitepec',
    'Cuyoaco',
    'Yehualtepec',
    'Tlanepantla',
    'Tochtepec',
    'Tlapacoya',
    'Tlaola',
    'Tlahuapan',
    'Chiautzingo',
    'Acatzingo',
    'Cuautlancingo',
    'Zihuateutla',
    'Hueyapan',
    'Atzala',
    'Cohuecan',
    'Chapulco',
    'San Matías Tlalancaleca',
    'Chiconcuautla',
    'San Nicolás de los Ranchos',
    'Cuayuca de Andrade',
    'Huehuetlán el Chico',
    'Coyomeapan',
    'Ajalpan',
    'Nicolás Bravo',
    'Cañada Morelos',
    'Nealtican',
    'Tianguismanalco',
    'Tochimilco',
    'Teteles de Avila Castillo',
    'Esperanza',
    'Huitziltepec',
    'Santa Inés Ahuatempan',
    'Acateno',
    'Ahuazotepec',
    'Chigmecatitlán',
    'Juan N. Méndez',
    'Petlalcingo',
    'Piaxtla',
    'San Juan Atzompa',
    'San Pedro Yeloixtlahuaca',
    'Santa Catarina Tlaltempan',
    'Tepetzintla',
    'Totoltepec de Guerrero',
    'Calpan',
    'Chignautla',
    'Chila',
    'Chila de la Sal',
    'Ahuehuetitla',
    'Tenampulco',
    'Molcaxac',
    'San Miguel Ixitlán',
    'Tecomatlán',
    'Zacapala',
    'Domingo Arenas',
    'San Pablo Anicano',
    'Tetela de Ocampo',
    'Tulcingo',
    'Axutla',
    'Juan Galindo',
    'Huaquechula',
    'Aquixtla',
    'Atempan',
    'Atlequizayan',
    'Camocuautla',
    'Caxhuacan',
    'Coatepec',
    'Cuetzalan del Progreso',
    'Hermenegildo Galeana',
    'Hueytlalpan',
    'Huitzilan de Serdán',
    'Ixtepec',
    'Jonotla',
    'Nauzontla',
    'Olintla',
    'Tepango de Rodríguez',
    'Tuzamapan de Galeana',
    'Xiutetelco',
    'Xochiapulco',
    'Xochitlán de Vicente Suárez',
    'Yaonáhuac',
    'Zapotitlán de Méndez',
    'Zongozotla',
    'Zoquiapan',
    'San Jerónimo Tecuanipan',
    'Santiago Miahuatlán',
    'Zacatlán',
    'Atexcal',
    'Aljojuca',
    'Chichiquila',
    'Rafael Lara Grajales',
    'Coatzingo',
    'Coronango',
    'Tlaltenango',
    'San Miguel Xoxtla',
    'San Martín Totoltepec',
    'Ahuatlán',
    'Epatlán',
    'Lafragua',
    'Nopalucan',
    'Acteopan',
    'Cohetzala',
    'San Diego la Mesa Tochimiltzingo',
    'San José Chiapa',
    'Tlapanalá',
    'Tepemaxalco',
    'Tepeojuma',
    'Tepexco',
    'Cuautinchán',
    'Pahuatlán',
    'Tlacuilotepec',
    'San Antonio Cañada',
    'San Salvador Huixcolotla',
    'Ixcaquixtla',
    'Tepatlaxco de Hidalgo',
    'Teotlalco',
    'Oriental',
    'Mazapiltepec de Juárez',
    'Soltepec',
    'Tlaxco',
    'Querétaro',
    'Corregidora',
    'San Joaquín',
    'Peñamiller',
    'Pedro Escobedo',
    'Tequisquiapan',
    'Colón',
    'Huimilpan',
    'Jalpan de Serra',
    'Ezequiel Montes',
    'El Marqués',
    'Amealco de Bonfil',
    'Pinal de Amoles',
    'Cadereyta de Montes',
    'Solidaridad',
    'Isla Mujeres',
    'José María Morelos',
    'Cozumel',
    'Felipe Carrillo Puerto',
    'Othón P. Blanco',
    'Puerto Morelos',
    'Tulum',
    'Bacalar',
    'Tamuín',
    'Villa de Arista',
    'Cárdenas',
    'Tamazunchale',
    'San Luis Potosí',
    'Venado',
    'Ciudad Valles',
    'Cerritos',
    'Salinas',
    'Tamasopo',
    'Xilitla',
    'Ciudad del Maíz',
    'Villa de Reyes',
    'Axtla de Terrazas',
    'Ebano',
    'Matehuala',
    'Ahualulco',
    'San Ciro de Acosta',
    'Vanegas',
    'Tancanhuitz',
    'Cedral',
    'Mexquitic de Carmona',
    'Santo Domingo',
    'Moctezuma',
    'Santa María del Río',
    'Villa de Arriaga',
    'Villa de Guadalupe',
    'Tampacán',
    'Huehuetlán',
    'Guadalcázar',
    'San Martín Chalchicuautla',
    'Tanquián de Escobedo',
    'San Vicente Tancuayalab',
    'Matlapa',
    'Charcas',
    'Aquismón',
    'Tampamolón Corona',
    'San Antonio',
    'Villa Juárez',
    'Soledad de Graciano Sánchez',
    'Villa de la Paz',
    'Cerro de San Pedro',
    'San Nicolás Tolentino',
    'Rioverde',
    'Ciudad Fernández',
    'Alaquines',
    'Villa de Ramos',
    'Tanlajás',
    'Catorce',
    'El Naranjo',
    'Tierra Nueva',
    'Armadillo de los Infante',
    'Mocorito',
    'Mazatlán',
    'Escuinapa',
    'Culiacán',
    'Guasave',
    'Navolato',
    'Ahome',
    'El Fuerte',
    'Concordia',
    'Salvador Alvarado',
    'San Ignacio',
    'Sinaloa',
    'Elota',
    'Angostura',
    'Choix',
    'Badiraguato',
    'Cosalá',
    'Agua Prieta',
    'San Luis Río Colorado',
    'Nacozari de García',
    'Hermosillo',
    'Cucurpe',
    'Altar',
    'Pitiquito',
    'Cajeme',
    'Etchojoa',
    'Bácum',
    'Huatabampo',
    'Guaymas',
    'Navojoa',
    'Empalme',
    'Caborca',
    'Sahuaripa',
    'Yécora',
    'General Plutarco Elías Calles',
    'Cananea',
    'Fronteras',
    'Puerto Peñasco',
    'Nogales',
    'Ures',
    'Baviácora',
    'Alamos',
    'La Colorada',
    'Bacanora',
    'Atil',
    'Quiriego',
    'Soyopa',
    'Bacoachi',
    'Tubutama',
    'Oquitoa',
    'Opodepe',
    'San Javier',
    'Villa Pesqueira',
    'Tepache',
    'Trincheras',
    'Banámichi',
    'Arizpe',
    'Aconchi',
    'Carbó',
    'Arivechi',
    'Naco',
    'Cumpas',
    'San Miguel de Horcasitas',
    'San Felipe de Jesús',
    'Suaqui Grande',
    'Benjamín Hill',
    'Imuris',
    'San Pedro de la Cueva',
    'Huépac',
    'Huachinera',
    'Huásabas',
    'San Ignacio Río Muerto',
    'Nácori Chico',
    'Granados',
    'Bavispe',
    'Bacadéhuachi',
    'Bacerac',
    'Divisaderos',
    'Onavas',
    'Santa Cruz',
    'Sáric',
    'Centro',
    'Centla',
    'Macuspana',
    'Jalapa',
    'Nacajuca',
    'Cunduacán',
    'Teapa',
    'Huimanguillo',
    'Comalcalco',
    'Tenosique',
    'Tacotalpa',
    'Jalpa de Méndez',
    'Paraíso',
    'Jonuta',
    'Balancán',
    'Tampico',
    'Río Bravo',
    'González',
    'Gustavo Díaz Ordaz',
    'Nuevo Morelos',
    'Reynosa',
    'Nuevo Laredo',
    'Ciudad Madero',
    'Altamira',
    'Padilla',
    'San Carlos',
    'Miguel Alemán',
    'Mier',
    'Mainero',
    'El Mante',
    'Antiguo Morelos',
    'Valle Hermoso',
    'Burgos',
    'Casas',
    'Güémez',
    'Llera',
    'Soto la Marina',
    'Xicoténcatl',
    'Cruillas',
    'Miquihuana',
    'Tula',
    'Palmillas',
    'Jaumave',
    'Tlaxcala',
    'Chiautempan',
    'Sanctórum de Lázaro Cárdenas',
    'El Carmen Tequexquitla',
    'Terrenate',
    'Tetla de la Solidaridad',
    'Apetatitlán de Antonio Carvajal',
    'Natívitas',
    'Calpulalpan',
    'Hueyotlipan',
    'Yauhquemehcan',
    'Zacatelco',
    'Tetlatlahuca',
    'Tzompantepec',
    'San Lorenzo Axocomanitla',
    'Santa Apolonia Teacalco',
    'Santa Catarina Ayometla',
    'Santa Cruz Quilehtla',
    'Ixtenco',
    'Nanacamilpa de Mariano Arista',
    'Acuamanala de Miguel Hidalgo',
    'Santa Cruz Tlaxcala',
    'Atltzayanca',
    'Apizaco',
    'Ixtacuixtla de Mariano Matamoros',
    'Contla de Juan Cuamatzi',
    'Xaltocan',
    'San Francisco Tetlanohcan',
    'Santa Isabel Xiloxoxtla',
    'Tepetitla de Lardizábal',
    'San Juan Huactzinco',
    'Xicohtzinco',
    'San Pablo del Monte',
    'Cuapiaxtla',
    'Huamantla',
    'Totolac',
    'Muñoz de Domingo Arenas',
    'Ziltlaltépec de Trinidad Sánchez Santos',
    'Xaloztoc',
    'San José Teacalco',
    'La Magdalena Tlaltelulco',
    'Santa Ana Nopalucan',
    'Españita',
    'Panotla',
    'Papalotla de Xicohténcatl',
    'Atlangatepec',
    'San Damián Texóloc',
    'Amaxac de Guerrero',
    'Mazatecochco de José María Morelos',
    'Teolocholco',
    'Cuaxomulco',
    'San Jerónimo Zacualpan',
    'Tepeyanco',
    'Tocatlán',
    'San Lucas Tecopilco',
    'Tlapacoyan',
    'Poza Rica de Hidalgo',
    'La Perla',
    'Nanchital de Lázaro Cárdenas del Río',
    'Paso de Ovejas',
    'Ixhuatlancillo',
    'Manlio Fabio Altamirano',
    'Veracruz',
    'Naranjos Amatlán',
    'Acayucan',
    'Perote',
    'San Andrés Tuxtla',
    'Isla',
    'Xalapa',
    'Córdoba',
    'Tlalixcoyan',
    'Espinal',
    'Río Blanco',
    'Hidalgotitlán',
    'Mariano Escobedo',
    'Amatlán de los Reyes',
    'San Juan Evangelista',
    'El Higo',
    'Coatzacoalcos',
    'Tlacojalpan',
    'Huatusco',
    'Cosoleacaque',
    'Tlacotalpan',
    'Pánuco',
    'Alvarado',
    'Soconusco',
    'Catemaco',
    'Juchique de Ferrer',
    'Boca del Río',
    'Coscomatepec',
    'Cosamaloapan de Carpio',
    'Las Choapas',
    'Medellín',
    'Pueblo Viejo',
    'Castillo de Teayo',
    'Coxquihui',
    'Maltrata',
    'Cuitláhuac',
    'Cotaxtla',
    'Agua Dulce',
    'Misantla',
    'Tezonapa',
    'Gutiérrez Zamora',
    'Uxpanapa',
    'Fortín',
    'Álamo Temapache',
    'Filomeno Mata',
    'Chumatlán',
    'Chicontepec',
    'Chinameca',
    'Cerro Azul',
    'Tlaltetela',
    'Tantoyuca',
    'Puente Nacional',
    'Playa Vicente',
    'Platón Sánchez',
    'Papantla',
    'José Azueta',
    'Tuxtilla',
    'Vega de Alatorre',
    'Juan Rodríguez Clara',
    'Landero y Coss',
    'Hueyapan de Ocampo',
    'Ixhuatlán del Café',
    'Ixmatlahuacan',
    'Xico',
    'Tres Valles',
    'Alto Lucero de Gutiérrez Barrios',
    'Cazones de Herrera',
    'Carlos A. Carrillo',
    'Altotonga',
    'Chacaltianguis',
    'Soledad de Doblado',
    'Jalacingo',
    'Jesús Carranza',
    'Las Vigas de Ramírez',
    'Otatitlán',
    'Paso del Macho',
    'Sayula de Alemán',
    'Ixhuatlán del Sureste',
    'Zozocolco de Hidalgo',
    'Santiago Tuxtla',
    'Saltabarranca',
    'Tlacolulan',
    'Angel R. Cabada',
    'La Antigua',
    'Ozuluama de Mascareñas',
    'Orizaba',
    'Naolinco',
    'Martínez de la Torre',
    'Jáltipan',
    'Tihuatlán',
    'Zongolica',
    'San Rafael',
    'Ursulo Galván',
    'Chiconquiaco',
    'Tancoco',
    'Sochiapa',
    'Chocamán',
    'Tamalín',
    'Banderilla',
    'Coetzala',
    'Lerdo de Tejada',
    'Nautla',
    'Tlacotepec de Mejía',
    'Camerino Z. Mendoza',
    'Tenochtitlán',
    'San Andrés Tenejapan',
    'Coacoatzintla',
    'Coyutla',
    'Ixcatepec',
    'Las Minas',
    'Coahuitlán',
    'Jalcomulco',
    'Tatatila',
    'Tepetlán',
    'Villa Aldama',
    'Ignacio de la Llave',
    'Amatitlán',
    'Omealca',
    'Ilamatlán',
    'Tonayán',
    'Soteapan',
    'Soledad Atzompa',
    'Ayahualulco',
    'Atzalan',
    'Astacinga',
    'Calcahualco',
    'Citlaltépetl',
    'Pajapan',
    'Ixhuatlán de Madero',
    'Chontla',
    'Miahuatlán',
    'Tenampa',
    'Apazapan',
    'Tantima',
    'Alpatláhuac',
    'Totutla',
    'Atlahuilco',
    'Tehuipango',
    'Ixhuacán de los Reyes',
    'Tatahuicapan de Juárez',
    'Mecayapan',
    'Cuichapa',
    'Teocelo',
    'Yanga',
    'Jamapa',
    'Rafael Delgado',
    'Acultzingo',
    'Naranjal',
    'Ixtaczoquitlán',
    'Huayacocotla',
    'Zontecomatlán de López y Fuentes',
    'Texcatepec',
    'Tlachichilco',
    'Cosautlán de Carvajal',
    'Moloacán',
    'Tlalnelhuayocan',
    'Yecuatla',
    'Tempoal',
    'Colipa',
    'Coatzintla',
    'Texistepec',
    'Huiloapan de Cuauhtémoc',
    'Tlaquilpa',
    'Comapa',
    'Tlilapan',
    'Zentla',
    'Mecatlán',
    'Tampico Alto',
    'Chalma',
    'Chiconamel',
    'Chinampa de Gorostiza',
    'Santiago Sochiapan',
    'Carrillo Puerto',
    'Mérida',
    'Tizimín',
    'Hoctún',
    'Muna',
    'Hunucmá',
    'Tepakán',
    'Dzoncauich',
    'Motul',
    'Ticul',
    'Umán',
    'Maxcanú',
    'Acanceh',
    'Cansahcab',
    'Peto',
    'Tekax',
    'Valladolid',
    'Tinum',
    'Tixkokob',
    'Izamal',
    'Chikindzonot',
    'Chankom',
    'Tixcacalcupul',
    'Yobaín',
    'Kaua',
    'Sotuta',
    'Cenotillo',
    'Tecoh',
    'Kantunil',
    'Panabá',
    'Mocochá',
    'Kanasín',
    'Telchac Puerto',
    'Dzemul',
    'Ixil',
    'Tahmek',
    'Conkal',
    'Sucilá',
    'Chapab',
    'Santa Elena',
    'Dzilam González',
    'Teya',
    'Tixpéhual',
    'Calotmul',
    'Celestún',
    'Chemax',
    'Cuncunul',
    'Dzitás',
    'Halachó',
    'Samahil',
    'Tekom',
    'Yaxcabá',
    'Quintana Roo',
    'Uayma',
    'Dzilam de Bravo',
    'Sudzal',
    'Tekal de Venegas',
    'Cacalchén',
    'Tetiz',
    'Dzidzantún',
    'Kinchil',
    'Mama',
    'Tzucacab',
    'Bokobá',
    'Chicxulub Pueblo',
    'Xocchel',
    'Muxupip',
    'Opichén',
    'Oxkutzcab',
    'Timucuy',
    'Tekit',
    'Sacalum',
    'Tahdziú',
    'Sanahcat',
    'Seyé',
    'Ucú',
    'Tunkás',
    'Tixmehuac',
    'Cuzamá',
    'Chacsinkín',
    'Cantamayec',
    'Chocholá',
    'Chumayel',
    'Akil',
    'Abalá',
    'Maní',
    'Mayapán',
    'Hocabá',
    'Homún',
    'Huhí',
    'Baca',
    'Buctzotz',
    'Chichimilá',
    'Espita',
    'Kopomá',
    'Río Lagartos',
    'Suma',
    'Temozón',
    'Teabo',
    'Yaxkukul',
    'Sinanché',
    'Tekantó',
    'Telchac Pueblo',
    'Temax',
    'Dzán',
    'Zacatecas',
    'Villa García',
    'Santa María de la Paz',
    'El Salvador',
    'Susticacán',
    'Nochistlán de Mejía',
    'Moyahua de Estrada',
    'Noria de Ángeles',
    'Fresnillo',
    'Sombrerete',
    'Calera',
    'Jerez',
    'Villanueva',
    'Ojocaliente',
    'Jalpa',
    'Juchipila',
    'Luis Moya',
    'Miguel Auza',
    'Pinos',
    'Río Grande',
    'Teúl de González Ortega',
    'Tlaltenango de Sánchez Román',
    'Chalchihuites',
    'Valparaíso',
    'Tepetongo',
    'Mazapil',
    'El Plateado de Joaquín Amaro',
    'Momax',
    'Sain Alto',
    'Vetagrande',
    'Mezquital del Oro',
    'Cañitas de Felipe Pescador',
    'Villa González Ortega',
    'General Pánfilo Natera',
    'Trinidad García de la Cadena',
    'General Francisco R. Murguía',
    'General Enrique Estrada',
    'Villa de Cos',
    'Concepción del Oro',
    'Atolinga',
    'Genaro Codina',
    'Trancoso',
    'Apozol',
    'Huanusco',
    'Monte Escobedo',
    'Tabasco',
    'Apulco',
    'Jiménez del Teul',
    'Tepechitlán',
    'Juan Aldama',
];