import Head from 'next/head';
import { FrequentQuestions, Statistics, Reviews } from '@/components';
import { BaseLayout } from '@/components';

export default function Home() {
  return (
    <>
      <Head>
        <title>NextApp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BaseLayout>
        <Statistics/>
        <FrequentQuestions/>
        <Reviews/>
      </BaseLayout>
    </>
  )
}
